language: ruby

rvm:
  - 2.4

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      script:
        - bundle exec rubocop

    - stage: test
      script:
        - bundle exec rake db:migrate
        - bundle exec rake db:setup
        - bundle exec rake spec

cache: bundler
